import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        appName: "TravelTales",
        tagline: "Your Personal AI Travel Agent",
        startPlanning: "Start Planning",
        viewDemo: "View Demo",
        heroTitle: "Travel Planning, Redefined",
        heroSubtitle: "Experience the future of travel. Beautiful, AI-crafted itineraries that learn from your vibe.",
        exploreDestinations: "Explore Destinations",
        features: "Features",
        pricing: "Pricing",
        savedTrips: "Saved Trips",
        // Features
        featureTitle: "Everything you need for the perfect trip",
        featureSub: "We combine advanced AI with local insights to create the perfect travel experience tailored just for you.",
        aiItineraries: "AI Itineraries",
        aiItinerariesDesc: "Generates full day-by-day plans based on your vibe, budget, and pace in seconds.",
        smartBudget: "Smart Budget",
        smartBudgetDesc: "Predict costs for flights, hotels, and daily expenses with real-time tracking.",
        crowdRadar: "Crowd Radar",
        crowdRadarDesc: "Know when to visit. Our AI predicts crowd levels so you can skip the lines.",
        hiddenGems: "Hidden Gems",
        hiddenGemsDesc: "Discover secret spots and local favorites that typical travel guides miss.",
        localIntel: "Local Intelligence",
        mapBased: "Map-Based Exploration",
        budgetManager: "Budget Manager",
        perPerson: "Per Person",
        totalTripCost: "Total Trip Cost",
        numTravelers: "NUMBER OF TRAVELERS",
        finalSplit: "Final Split",
        dayWiseBudget: "Day-wise Budget Forecast",
        groupBudgetAlert: "over group budget",
        reset: "Reset to original travelers",
        mustDo: "Must Do",
        safeToSkip: "Safe to Skip",
        fomoLevel: "FOMO LEVEL",
        morning: "Morning 🌅",
        afternoon: "Afternoon ☀️",
        evening: "Evening 🌙",
        highlights: "Highlights",
        savePdf: "Save PDF",
        share: "Share",
        // Onboarding
        letPlanTrip: "Let's Plan Your Trip",
        onboardingSub: "Tell us a bit about your travel plans so AI can work its magic.",
        whereTo: "Where to?",
        whereToSub: "City, Region, or Country",
        destPlaceholder: "e.g., Kyoto, Japan",
        whenGoing: "When are you going?",
        whenGoingSub: "We'll check for weekends & festivals.",
        startDate: "Start Date",
        endDate: "End Date",
        whoComing: "Who's coming with you?",
        whoComingSub: "Helps suggest activities.",
        vibe: "What's the vibe?",
        vibeSub: "Personalize your style.",
        budgetPref: "Budget Preference",
        budgetSub: "Saving or Splurging?",
        low: "Low",
        medium: "Medium",
        premium: "Premium",
        interests: "Interests",
        interestsSub: "Select all that apply.",
        constraints: "Constraints",
        constraintsSub: "Any limitations?",
        safetyComfort: "Safety & Comfort (Optional but Powerful)",
        safetyComfortSub: "Your well-being matters.",
        generatePlan: "Generate My Plan",
        generating: "Generating...",
        fillBasicsAlert: "Please fill in the basics (Destination & Dates)!",
        // Trip Plan
        noPlanFound: "No Plan Found",
        tripVibe: "Trip",
        total: "Total",
        day: "Day",
        weather: "Weather",
        hours: "Hours",
        entryCost: "Entry Cost",
        holidays: "Holidays",
        travelTime: "Travel Time",
        warningsTips: "Warnings & Tips",
        gotIt: "Got it!",
        budgetAnalysis: "Analyzed expenses for your trip",
        forecastFor: "Forecast for",
        traveler: "traveler",
        travelersLabel: "travelers",
        away: "away",
        saved: "Saved!",
        copyAlert: "Link copied to clipboard!",
        // Local Intel
        localIntelTitle: "Local Intelligence",
        insiderTipsFor: "Insider tips for",
        food: "Food",
        transport: "Transport",
        guides: "Guides",
        localSpecialties: "Local Specialties",
        recommendedSpots: "Recommended Spots",
        routes: "Routes",
        passes: "Passes",
        keyContacts: "Key Contacts",
        specialtyLabel: "Specialty",
        languagesLabel: "Languages",
        // Map
        mapExploration: "Map Exploration",
        places: "Places",
        rental: "Rental",
        emergency: "Emergency",
        interactiveMap: "Interactive Map",
        budgetCurrencyTitle: "Budget & Currency",
        selectYourCurrency: "Select Your Currency",
        currencyConverter: "Currency Converter",
        from: "From",
        to: "To",
        amount: "Amount",
        convert: "Convert",
        convertedAmount: "Converted Amount",
        baseCurrency: "Base Currency (USD)",
        viewDetailedBudget: "View Detailed Budget",
        dayWiseForecast: "Day-wise Forecast",
        backToTrip: "Back to Trip",
        ratesDisclaimer: "Rates are updated in real-time. Please note that actual bank rates may vary.",
        exactTravelerCount: "Or enter exact number of travelers",
        personWiseSplit: "Person-wise Split",
        staySuggestions: "Stay Suggestions",
        stayDesc: "Explore handpicked accommodations matching your budget.",
        viewStays: "Explore Hotels",
        staysIn: "Stay Suggestions in",
        handpickedHotels: "Handpicked accommodations for your vibe",
        perNight: "per night",
        viewDetails: "View Details",
        availableRooms: "Available Rooms",
        amenities: "Amenities",
        contactNow: "Contact Now",
        phone: "Phone",
        address: "Address",
        close: "Close",
        contactDetails: "Contact Information",
        backToDetails: "Back to Details",
        aiMagic: "AI Magic",
        smartReschedule: "Smart Reschedule",
        crowdSimulator: "Crowd Simulator",
        crowdDensity: "Crowd Density",
        bestTimeVisit: "Best time to visit",
        rebalancingPlan: "Real-Time Rebalancing",
        wakeUpLate: "Wake up late?",
        skippedPlace: "Skipped place?",
        overspent: "Overspent?",
        rescheduleTip: "AI will auto-adjust your day...",
        alternative: "Alternative",
        simulatedCrowd: "Simulated Density"
    },
    es: {
        appName: "TravelTales",
        tagline: "Tu Agente de Viajes con IA Personal",
        startPlanning: "Empieza a Planificar",
        viewDemo: "Ver Demo",
        heroTitle: "Planificación de Viajes, Redefinida",
        heroSubtitle: "Experimenta el futuro de los viajes. Itinerarios hermosos creados por IA que aprenden de tu estilo.",
        exploreDestinations: "Explorar Destinos",
        features: "Características",
        pricing: "Precios",
        savedTrips: "Viajes Guardados",
        featureTitle: "Todo lo que necesitas para el viaje perfecto",
        featureSub: "Combinamos IA avanzada con información local para crear la experiencia de viaje perfecta adaptada solo a ti.",
        aiItineraries: "Itinerarios de IA",
        aiItinerariesDesc: "Genera planes diarios completos basados en tu estilo, presupuesto y ritmo en segundos.",
        smartBudget: "Presupuesto Inteligente",
        smartBudgetDesc: "Predice costes de vuelos, hoteles y gastos diarios con seguimiento en tiempo real.",
        crowdRadar: "Radar de Multitudes",
        crowdRadarDesc: "Sabe cuándo visitar. Nuestra IA predice los niveles de multitud para que puedas evitar las colas.",
        hiddenGems: "Joyas Ocultas",
        hiddenGemsDesc: "Descubre lugares secretos y favoritos locales que las guías de viaje típicas pasan por alto.",
        budgetManager: "Gestor de Presupuesto Inteligente",
        localIntel: "Inteligencia Local",
        mapBased: "Exploración basada en Mapas",
        perPerson: "Por Persona",
        totalTripCost: "Costo Total del Viaje",
        numTravelers: "NÚMERO DE VIAJEROS",
        finalSplit: "División Final",
        dayWiseBudget: "Pronóstico de Presupuesto Diario",
        groupBudgetAlert: "sobre el presupuesto grupal",
        reset: "Restablecer a viajeros originales",
        mustDo: "Imprescindible",
        safeToSkip: "Se puede omitir",
        fomoLevel: "NIVEL DE FOMO",
        morning: "Mañana 🌅",
        afternoon: "Tarde ☀️",
        evening: "Noche 🌙",
        highlights: "Destacados",
        savePdf: "Guardar PDF",
        share: "Compartir",
        letPlanTrip: "Planifiquemos tu Viaje",
        onboardingSub: "Cuéntanos un poco sobre tus planes de viaje para que la IA haga su magia.",
        whereTo: "¿A dónde vas?",
        whereToSub: "Ciudad, Región o País",
        destPlaceholder: "ej., Kioto, Japón",
        whenGoing: "¿Cuándo vas?",
        whenGoingSub: "Revisaremos fines de semana y festivales.",
        startDate: "Fecha de inicio",
        endDate: "Fecha de fin",
        whoComing: "¿Quién te acompaña?",
        whoComingSub: "Ayuda a sugerir actividades.",
        vibe: "¿Cuál es el ambiente?",
        vibeSub: "Personaliza tu estilo.",
        budgetPref: "Preferencia de presupuesto",
        budgetSub: "¿Ahorrar o gastar?",
        low: "Bajo",
        medium: "Medio",
        premium: "Premium",
        interests: "Intereses",
        interestsSub: "Selecciona todo lo que aplique.",
        constraints: "Limitaciones",
        constraintsSub: "¿Alguna restricción?",
        safetyComfort: "Seguridad y Confort (Opcional)",
        safetyComfortSub: "Tu bienestar importa.",
        generatePlan: "Generar mi plan",
        generating: "Generando...",
        fillBasicsAlert: "¡Por favor completa lo básico (Destino y Fechas)!",
        noPlanFound: "No se encontró ningún plan",
        tripVibe: "Viaje",
        total: "Total",
        day: "Día",
        weather: "Clima",
        hours: "Horario",
        entryCost: "Costo de entrada",
        holidays: "Días festivos",
        travelTime: "Tiempo de viaje",
        warningsTips: "Advertencias y consejos",
        gotIt: "¡Entendido!",
        budgetAnalysis: "Gastos analizados para su viaje",
        forecastFor: "Previsión para",
        traveler: "viajero",
        travelersLabel: "viajeros",
        away: "de distancia",
        saved: "¡Guardado!",
        copyAlert: "¡Enlace copiado al portapapeles!",
        localIntelTitle: "Inteligencia Local",
        insiderTipsFor: "Consejos de expertos para",
        food: "Comida",
        transport: "Transporte",
        guides: "Guías",
        localSpecialties: "Especialidades Locales",
        recommendedSpots: "Lugares Recomendados",
        routes: "Rutas",
        passes: "Pases",
        keyContacts: "Contactos Clave",
        specialtyLabel: "Especialidad",
        languagesLabel: "Idiomas",
        mapExploration: "Exploración del Mapa",
        places: "Lugares",
        rental: "Alquiler",
        emergency: "Emergencias",
        interactiveMap: "Mapa Interactivo",
        budgetCurrencyTitle: "Presupuesto y Moneda",
        selectYourCurrency: "Seleccione su Moneda",
        currencyConverter: "Convertidor de Moneda",
        from: "De",
        to: "A",
        amount: "Cantidad",
        convert: "Convertir",
        convertedAmount: "Cantidad Convertida",
        baseCurrency: "Moneda Base (USD)",
        viewDetailedBudget: "Ver Presupuesto Detallado",
        dayWiseForecast: "Pronóstico Diario",
        backToTrip: "Volver al Viaje",
        ratesDisclaimer: "Las tasas se actualizan en tiempo real. Tenga en cuenta que las tasas bancarias reales pueden variar.",
        exactTravelerCount: "O ingrese el número exacto de viajeros",
        personWiseSplit: "División por persona",
        staySuggestions: "Sugerencias de estancia",
        stayDesc: "Explora alojamientos seleccionados de acuerdo a tu presupuesto.",
        viewStays: "Explorar Hoteles",
        staysIn: "Sugerencias de estancia en",
        handpickedHotels: "Alojamientos seleccionados para tu estilo",
        perNight: "por noche",
        viewDetails: "Ver detalles",
        availableRooms: "Habitaciones disponibles",
        amenities: "Servicios",
        contactNow: "Contactar ahora",
        phone: "Teléfono",
        address: "Dirección",
        close: "Cerrar",
        contactDetails: "Información de contacto",
        backToDetails: "Volver a detalles",
        aiMagic: "Magia de IA",
        smartReschedule: "Reprogramación Inteligente",
        crowdSimulator: "Simulador de Multitudes",
        crowdDensity: "Densidad de Multitud",
        bestTimeVisit: "Mejor momento para visitar",
        rebalancingPlan: "Reequilibrio en Tiempo Real",
        wakeUpLate: "¿Te despertaste tarde?",
        skippedPlace: "¿Lugar saltado?",
        overspent: "¿Gastaste de más?",
        rescheduleTip: "La IA ajustará automáticamente tu día...",
        alternative: "Alternativa",
        simulatedCrowd: "Densidad Simulada"
    },
    hi: {
        appName: "TravelTales",
        tagline: "आपका निजी AI ट्रैवल एजेंट",
        startPlanning: "योजना शुरू करें",
        viewDemo: "डेमो देखें",
        heroTitle: "यात्रा योजना, नए सिरे से",
        heroSubtitle: "यात्रा के भविष्य का अनुभव करें। सुंदर, AI-निर्मित यात्रा कार्यक्रम जो आपकी शैली से सीखते हैं।",
        exploreDestinations: "गंतव्यों का अन्वेषण करें",
        features: "विशेषताएं",
        pricing: "मूल्य निर्धारण",
        savedTrips: "सहेजी गई यात्राएं",
        featureTitle: "एक आदर्श यात्रा के लिए आपको जो कुछ भी चाहिए",
        featureSub: "हम आपके लिए विशेष रूप से तैयार किए गए उत्तम यात्रा अनुभव बनाने के लिए उन्नत AI को स्थानीय अंतर्दृष्टि के साथ जोड़ते हैं।",
        aiItineraries: "AI यात्रा कार्यक्रम",
        aiItinerariesDesc: "सेकंड में आपकी शैली, बजट और गति के आधार पर पूर्ण दिन-प्रतिदिन की योजनाएँ उत्पन्न करता है।",
        smartBudget: "स्मार्ट बजट",
        smartBudgetDesc: "वास्तविक समय ट्रैकिंग के साथ उड़ानों, होटलों और दैनिक खर्चों के लिए लागत की भविष्यवाणी करें।",
        crowdRadar: "भीड़ रडार",
        crowdRadarDesc: "जानें कि कब जाना है। हमारा AI भीड़ के स्तर की भविष्यवाणी करता है ताकि आप लाइनों को छोड़ सकें।",
        hiddenGems: "छिपे हुए रत्न",
        hiddenGemsDesc: "गुप्त स्थानों और स्थानीय पसंदीदा खोजें जिन्हें विशिष्ट यात्रा गाइड याद कर देते हैं।",
        budgetManager: "स्मार्ट बजट प्रबंधक",
        localIntel: "स्थानीय खुफिया",
        mapBased: "मानचित्र-आधारित अन्वेषण",
        perPerson: "प्रति व्यक्ति",
        totalTripCost: "कुल यात्रा लागत",
        numTravelers: "यात्रियों की संख्या",
        finalSplit: "अंतिम विभाजन",
        dayWiseBudget: "दैनिक बजट पूर्वानुमान",
        groupBudgetAlert: "समूह बजट से अधिक",
        reset: "मूल यात्रियों पर रीसेट करें",
        mustDo: "ज़रूरी काम",
        safeToSkip: "छोड़ने के लिए सुरक्षित",
        fomoLevel: "फोमो स्तर",
        morning: "सुबह 🌅",
        afternoon: "दोपहर ☀️",
        evening: "शाम 🌙",
        highlights: "मुख्य विशेषताएं",
        savePdf: "पीडीएफ सहेजें",
        share: "साझा करें",
        letPlanTrip: "आइए आपकी यात्रा की योजना बनाएं",
        onboardingSub: "हमें अपनी यात्रा योजनाओं के बारे में थोड़ा बताएं ताकि AI अपना जादू चला सके।",
        whereTo: "कहाँ जाना है?",
        whereToSub: "शहर, क्षेत्र या देश",
        destPlaceholder: "जैसे, क्योटो, जापान",
        whenGoing: "आप कब जा रहे हैं?",
        whenGoingSub: "हम सप्ताहांत और त्योहारों की जांच करेंगे।",
        startDate: "आरंभ तिथि",
        endDate: "अंतिम तिथि",
        whoComing: "आपके साथ कौन आ रहा है?",
        whoComingSub: "गतिविधियों का सुझाव देने में मदद करता है।",
        vibe: "वाइब क्या है?",
        vibeSub: "अपनी शैली को निजीकृत करें।",
        budgetPref: "बजट प्राथमिकता",
        budgetSub: "बचत या खर्च?",
        low: "कम",
        medium: "मध्यम",
        premium: "प्रीमियम",
        interests: "रुचियां",
        interestsSub: "वे सभी चुनें जो लागू हों।",
        constraints: "बाधाएं",
        constraintsSub: "कोई सीमाएँ?",
        safetyComfort: "सुरक्षा और आराम (वैकल्पिक)",
        safetyComfortSub: "आपका कल्याण मायने रखता।",
        generatePlan: "मेरी योजना तैयार करें",
        generating: "तैयार हो रहा है...",
        fillBasicsAlert: "कृपया मूल बातें (गंतव्य और तिथियां) भरें!",
        noPlanFound: "कोई योजना नहीं मिली",
        tripVibe: "यात्रा",
        total: "कुल",
        day: "दिन",
        weather: "मौसम",
        hours: "घंटे",
        entryCost: "प्रवेश शुल्क",
        holidays: "छुटिट्यां",
        travelTime: "यात्रा का समय",
        warningsTips: "चेतावनी और सुझाव",
        gotIt: "समझ गया!",
        budgetAnalysis: "आपकी यात्रा के लिए खर्चों का विश्लेषण किया गया",
        forecastFor: "पूर्वानुमान के लिए",
        traveler: "यात्री",
        travelersLabel: "यात्रियों",
        away: "दूर",
        saved: "सहेजा गया!",
        copyAlert: "लिंक क्लिपबोर्ड पर कॉपी किया गया!",
        localIntelTitle: "स्थानीय जानकारी",
        insiderTipsFor: "के लिए अंदरूनी सूत्र सुझाव",
        food: "भोजन",
        transport: "परिवहन",
        guides: "गाइड",
        localSpecialties: "स्थानीय विशेषता",
        recommendedSpots: "अनुशंसित स्थान",
        routes: "मार्ग",
        passes: "पास",
        keyContacts: "महत्वपूर्ण संपर्क",
        specialtyLabel: "विशेषज्ञता",
        languagesLabel: "भाषाएं",
        mapExploration: "मानचित्र अन्वेषण",
        places: "स्थान",
        rental: "किराया",
        emergency: "आपातकालीन",
        interactiveMap: "इंटरैक्टिव मानचित्र",
        budgetCurrencyTitle: "बजट और मुद्रा",
        selectYourCurrency: "अपनी मुद्रा चुनें",
        currencyConverter: "मुद्रा परिवर्तक",
        from: "से",
        to: "को",
        amount: "राशि",
        convert: "बदलें",
        convertedAmount: "परिवर्तित राशि",
        baseCurrency: "आधार मुद्रा (USD)",
        viewDetailedBudget: "विस्तृत बजट देखें",
        dayWiseForecast: "दिन-वार पूर्वानुमान",
        backToTrip: "यात्रा पर वापस",
        ratesDisclaimer: "दरें रीयल-टाइम में अपडेट की जाती हैं। कृपया ध्यान दें कि वास्तविक बैंक दरें भिन्न हो सकती हैं।",
        exactTravelerCount: "या यात्रियों की सही संख्या दर्ज करें",
        personWiseSplit: "व्यक्ति-वार विभाजन",
        staySuggestions: "रुकने के सुझाव",
        stayDesc: "अपने बजट के अनुसार चुने हुए आवास देखें।",
        viewStays: "होटल खोजें",
        staysIn: "रुकने के लिए सुझाव",
        handpickedHotels: "आपकी पसंद के अनुसार चुने हुए होटल",
        perNight: "प्रति रात",
        viewDetails: "विवरण देखें",
        availableRooms: "उपलब्ध कमरे",
        amenities: "सुविधाएं",
        contactNow: "अभी संपर्क करें",
        phone: "फ़ोन",
        address: "पता",
        close: "बंद करें",
        contactDetails: "संपर्क जानकारी",
        backToDetails: "विवरण पर वापस",
        aiMagic: "AI जादू",
        smartReschedule: "स्मार्ट समय निर्धारण",
        crowdSimulator: "भीड़ सिम्युलेटर",
        crowdDensity: "भीड़ का घनत्व",
        bestTimeVisit: "घूमने का सबसे अच्छा समय",
        rebalancingPlan: "रीयल-टाइम रिबैलेंसिंग",
        wakeUpLate: "देर से सोकर उठे?",
        skippedPlace: "जगह छोड़ दी?",
        overspent: "ज़्यादा खर्च हो गया?",
        rescheduleTip: "AI आपके दिन को ऑटो-एडजस्ट करेगा...",
        alternative: "विकल्प",
        simulatedCrowd: "नकली भीड़ घनत्व"
    },
    ru: {
        appName: "TravelTales",
        tagline: "Ваш личный ИИ-турагент",
        startPlanning: "Начать планирование",
        viewDemo: "Посмотреть демо",
        heroTitle: "Планирование путешествий по-новому",
        heroSubtitle: "Почувствуйте будущее путешествий. Красивые маршруты, созданные ИИ, которые изучают ваш стиль.",
        exploreDestinations: "Исследовать направления",
        features: "Возможности",
        pricing: "Цены",
        savedTrips: "Сохраненные поездки",
        featureTitle: "Все, что нужно для идеальной поездки",
        featureSub: "Мы сочетаем передовой ИИ с местными знаниями, чтобы создать идеальное путешествие специально для вас.",
        aiItineraries: "ИИ-маршруты",
        aiItinerariesDesc: "Создает полные планы по дням на основе вашего стиля, бюджета и темпа за считанные секунды.",
        smartBudget: "Умный бюджет",
        smartBudgetDesc: "Прогнозируйте расходы на перелеты, отели и ежедневные траты с отслеживанием в реальном времени.",
        crowdRadar: "Радар толпы",
        crowdRadarDesc: "Знайте, когда ехать. Наш ИИ прогнозирует уровень загруженности, чтобы вы могли избежать очередей.",
        hiddenGems: "Скрытые жемчужины",
        hiddenGemsDesc: "Откройте для себя секретные места и любимые заведения местных жителей, которые пропускают обычные путеводители.",
        budgetManager: "Умный менеджер бюджета",
        localIntel: "Местная информация",
        mapBased: "Исследование на карте",
        perPerson: "На человека",
        totalTripCost: "Общая стоимость поездки",
        numTravelers: "КОЛИЧЕСТВО ПУТЕШЕСТВЕННИКОВ",
        finalSplit: "Итоговое разделение",
        dayWiseBudget: "Прогноз ежедневного бюджета",
        groupBudgetAlert: "превышение бюджета группы",
        reset: "Сбросить до исходных путешественников",
        mustDo: "Обязательно к посещению",
        safeToSkip: "Можно пропустить",
        fomoLevel: "УРОВЕНЬ FOMO",
        morning: "Утро 🌅",
        afternoon: "День ☀️",
        evening: "Вечер 🌙",
        highlights: "Главное",
        savePdf: "Сохранить PDF",
        share: "Поделиться",
        letPlanTrip: "Давайте спланируем вашу поездку",
        onboardingSub: "Расскажите немного о своих планах, чтобы ИИ мог сотворить чудо.",
        whereTo: "Куда едем?",
        whereToSub: "Город, регион или страна",
        destPlaceholder: "напр., Киото, Япония",
        whenGoing: "Когда едете?",
        whenGoingSub: "Мы проверим выходные и фестивали.",
        startDate: "Дата начала",
        endDate: "Дата окончания",
        whoComing: "Кто едет с вами?",
        whoComingSub: "Помогает предложить мероприятия.",
        vibe: "Какая атмосфера?",
        vibeSub: "Персонализируйте свой стиль.",
        budgetPref: "Бюджетные предпочтения",
        budgetSub: "Экономим или шикуем?",
        low: "Низкий",
        medium: "Средний",
        premium: "Премиум",
        interests: "Интересы",
        interestsSub: "Выберите всё, что подходит.",
        constraints: "Ограничения",
        constraintsSub: "Есть ли ограничения?",
        safetyComfort: "Безопасность и комфорт (опционально)",
        safetyComfortSub: "Ваше благополучие имеет значение.",
        generatePlan: "Создать мой план",
        generating: "Создание...",
        fillBasicsAlert: "Пожалуйста, заполните основные данные (место и даты)!",
        noPlanFound: "План не найден",
        tripVibe: "Поездка",
        total: "Итого",
        day: "День",
        weather: "Погода",
        hours: "Часы работы",
        entryCost: "Стоимость входа",
        holidays: "Выходные",
        travelTime: "Время в пути",
        warningsTips: "Предупреждения и советы",
        gotIt: "Понятно!",
        budgetAnalysis: "Проанализированные расходы на поездку",
        forecastFor: "Прогноз для",
        traveler: "путешественник",
        travelersLabel: "путешественников",
        away: "вдали",
        saved: "Сохранено!",
        copyAlert: "Ссылка скопирована в буфер обмена!",
        localIntelTitle: "Местная информация",
        insiderTipsFor: "Инсайдерские советы для",
        food: "Еда",
        transport: "Транспорт",
        guides: "Гиды",
        localSpecialties: "Местные деликатесы",
        recommendedSpots: "Рекомендуемые места",
        routes: "Маршруты",
        passes: "Проездные",
        keyContacts: "Важные контакты",
        specialtyLabel: "Специализация",
        languagesLabel: "Языки",
        mapExploration: "Исследование карты",
        places: "Места",
        rental: "Аренда",
        emergency: "Чрезвычайные ситуации",
        interactiveMap: "Интерактивная карта",
        budgetCurrencyTitle: "Бюджет и валюта",
        selectYourCurrency: "Выберите валюту",
        currencyConverter: "Конвертер валют",
        from: "Из",
        to: "В",
        amount: "Сумма",
        convert: "Конвертировать",
        convertedAmount: "Конвертированная сумма",
        baseCurrency: "Базовая валюта (USD)",
        viewDetailedBudget: "Посмотреть подробный бюджет",
        dayWiseForecast: "Прогноз по дням",
        backToTrip: "Назад к поездке",
        ratesDisclaimer: "Курсы обновляются в реальном времени. Обратите внимание, что фактические банковские курсы могут отличаться.",
        exactTravelerCount: "Или введите точное количество путешественников",
        personWiseSplit: "Распределение по лицам",
        staySuggestions: "Варианты проживания",
        stayDesc: "Посмотрите специально подобранное жилье под ваш бюджет.",
        viewStays: "Посмотреть отели",
        staysIn: "Варианты проживания в",
        handpickedHotels: "Специально подобранное жилье под ваш стиль",
        perNight: "за ночь",
        viewDetails: "Подробнее",
        availableRooms: "Доступные номера",
        amenities: "Удобства",
        contactNow: "Связаться сейчас",
        phone: "Телефон",
        address: "Адрес",
        close: "Закрыть",
        contactDetails: "Контактная информация",
        backToDetails: "Назад к описанию",
        aiMagic: "Магия ИИ",
        smartReschedule: "Умное расписание",
        crowdSimulator: "Симулятор толпы",
        crowdDensity: "Плотность толпы",
        bestTimeVisit: "Лучшее время для посещения",
        rebalancingPlan: "Перепланирование в реальном времени",
        wakeUpLate: "Проспали?",
        skippedPlace: "Пропустили место?",
        overspent: "Потратили больше?",
        rescheduleTip: "ИИ автоматически подстроит ваш день...",
        alternative: "Альтернатива",
        simulatedCrowd: "Симулированная плотность"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
