import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
    ArrowLeft, Sun, Download, Share2, DollarSign, Clock, MapPin,
    Ticket, Frown, X, AlertTriangle, Calendar, Info, Wallet, ArrowRight, Home, Users, Zap
} from 'lucide-react';

import MapExploration from './MapExploration';
import LocalIntelligence from './LocalIntelligence';
import LiveContext from './LiveContext';
import { useLanguage } from './LanguageContext';

const TripPlan = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const { t, language } = useLanguage();
    const { plan } = location.state || {};
    const [selectedActivity, setSelectedActivity] = useState(null);
    const [isSaved, setIsSaved] = useState(false);
    const [magicResult, setMagicResult] = useState(null);

    const languages = [
        { code: 'en', name: 'English' },
        { code: 'es', name: 'Español' },
        { code: 'fr', name: 'Français' },
        { code: 'zh', name: '中文' },
        { code: 'ar', name: 'العربية' },
        { code: 'hi', name: 'हिन्दी' },
        { code: 'de', name: 'Deutsch' },
        { code: 'pt', name: 'Português' },
        { code: 'ja', name: '日本語' },
        { code: 'ru', name: 'Русский' }
    ];

    const handleSave = () => {
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 3000);
        window.print();
    };
    const handleShare = () => {
        const text = `Check out my ${plan.tripName}! Plan generated by TravelTales.`;
        if (navigator.share) {
            navigator.share({
                title: plan.tripName,
                text: text,
                url: window.location.href,
            });
        } else {
            navigator.clipboard.writeText(`${text} ${window.location.href}`);
            alert(t('copyAlert') || 'Shared link copied to clipboard!');
        }
    };

    const handleMagicClick = (type) => {
        console.log('🧠 AI Magic triggered:', type);
        console.log('Plan itinerary:', plan?.itinerary);

        if (!plan || !plan.itinerary || plan.itinerary.length === 0) {
            console.error('No itinerary data available');
            return;
        }

        const day = plan.itinerary[0];
        console.log('Day data:', day);

        // Try to find a slot with smartAlternatives
        let slot = null;
        if (day.morning?.smartAlternatives) {
            slot = day.morning;
        } else if (day.afternoon?.smartAlternatives) {
            slot = day.afternoon;
        } else if (day.evening?.smartAlternatives) {
            slot = day.evening;
        }

        console.log('Selected slot:', slot);

        // Enhanced fallback messages if data is missing
        const fallbackMessages = {
            late: "🌅 No worries! Shift your morning plans to late afternoon (3-5 PM) when crowds thin out. Grab brunch at a local café first, then head straight to your top priority spot. Pro tip: Skip souvenir shopping to save 30+ minutes!",
            skipped: "🎨 Try the neighborhood's hidden gem instead: the local artisan quarter! Just 15 mins away, you'll find authentic street food, live music, and handmade crafts. Locals say it's the real heart of the city - and it's free to explore!",
            overspent: "💰 Smart move! Switch to the free walking tour of the historic district (tips-based, starts every 2 hours). Pack a picnic from the corner market ($8 vs $40 restaurant), and you'll save money while experiencing authentic local life. Win-win!"
        };

        const alternative = slot?.smartAlternatives?.[type] || fallbackMessages[type] || "AI is analyzing your schedule...";

        setMagicResult({
            type,
            title: slot?.title || 'Your Schedule',
            alternative
        });

        setTimeout(() => setMagicResult(null), 8000);
    };

    if (!plan) {
        return (
            <div className="flex justify-center items-center" style={{ minHeight: '100vh', background: 'var(--bg-body)' }}>
                <div className="text-center">
                    <h2>{t('noPlanFound')}</h2>
                    <button onClick={() => navigate('/plan')} className="btn btn-primary" style={{ marginTop: '1rem' }}>
                        {t('startPlanning')}
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div style={{ minHeight: '100vh', paddingBottom: '5rem', background: '#F8FAFC', paddingTop: '80px' }}>
            {/* Header Image */}
            <div className="trip-header" style={{
                height: '350px',
                background: `linear-gradient(to top, rgba(0,0,0,0.8), transparent), url(${plan.coverImage || 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80'}) center/cover`,
                position: 'relative',
                color: 'white',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'flex-end',
                paddingBottom: '3rem'
            }}>
                <div className="container" style={{ position: 'relative', zIndex: 2 }}>
                    <button
                        onClick={() => navigate('/plan')}
                        style={{
                            position: 'absolute', top: '-130px', left: '0',
                            background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)',
                            border: 'none', borderRadius: '50%', width: '40px', height: '40px',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            cursor: 'pointer', color: 'white'
                        }}
                    >
                        <ArrowLeft size={24} />
                    </button>

                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                        <div className="flex gap-2" style={{ marginBottom: '1rem' }}>
                            <span style={{ background: 'var(--primary)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold', textTransform: 'uppercase' }}>
                                {plan.vibe} {t('tripVibe')}
                            </span>
                            <span style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold' }}>
                                {plan.dates}
                            </span>
                            {plan.timezone !== undefined && (
                                <span style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold' }}>
                                    🕒 {new Date(new Date().getTime() + (plan.timezone * 1000) + (new Date().getTimezoneOffset() * 60000)).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} Local Time
                                </span>
                            )}
                        </div>
                        <h1 style={{ color: 'white', marginBottom: '0.5rem', fontSize: '4rem' }}>{plan.destination}</h1>
                        <p style={{ fontSize: '1.2rem', opacity: 0.9 }}>
                            Your personalized {plan.travelers} adventure. Est. Budget: <span style={{ color: '#86EFAC', fontWeight: 'bold' }}>${plan.budgetSummary.total} {t('total')}</span>
                        </p>
                    </motion.div>
                </div>
            </div>

            <div className="container" style={{ marginTop: '-3rem', position: 'relative', zIndex: 10 }}>
                {/* 5️⃣ Map-Based Exploration */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    style={{ marginBottom: '2rem' }}
                >
                    <MapExploration plan={plan} />
                </motion.div>

                <div className="trip-grid" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 2fr) minmax(0, 1.2fr)', gap: '2rem' }}>

                    {/* Itinerary Column */}
                    <div className="itinerary-list">
                        {plan.itinerary.map((day, index) => (
                            <motion.div
                                key={day.day}
                                className="day-card"
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: index * 0.1 }}
                            >
                                {/* Day Header */}
                                <div className="day-header">
                                    <div>
                                        <h3 style={{ margin: 0 }}>{t('day')} {day.day}</h3>
                                        <p style={{ margin: 0, fontSize: '0.9rem' }}>{day.date}</p>
                                    </div>
                                    <div className="chip" style={{ background: 'white', fontSize: '0.85rem' }}>
                                        <Sun size={16} style={{ color: '#F59E0B' }} /> {day.weather}
                                    </div>
                                </div>

                                {/* Timeline Grid - Full Day Schedule */}
                                <div className="timeline-grid">
                                    {day.wakeup && <ActivitySlot label="🌅 Wake-up" data={day.wakeup} onSelect={setSelectedActivity} t={t} />}
                                    {day.breakfast && <ActivitySlot label="🍳 Breakfast" data={day.breakfast} onSelect={setSelectedActivity} t={t} />}
                                    <ActivitySlot label={t('morning')} data={day.morning} onSelect={setSelectedActivity} t={t} />
                                    {day.lunch && <ActivitySlot label="🍽️ Lunch" data={day.lunch} onSelect={setSelectedActivity} t={t} />}
                                    <ActivitySlot label={t('afternoon')} data={day.afternoon} onSelect={setSelectedActivity} t={t} />
                                    <ActivitySlot label={t('evening')} data={day.evening} onSelect={setSelectedActivity} t={t} />
                                    {day.dinner && <ActivitySlot label="🍷 Dinner" data={day.dinner} onSelect={setSelectedActivity} t={t} />}
                                </div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Sidebar */}
                    <div className="sidebar" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                        {/* 💰 Budget Analysis Redirect */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            className="card"
                            style={{
                                background: 'linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%)',
                                color: 'white',
                                display: 'flex',
                                flexDirection: 'column',
                                gap: '1rem',
                                padding: '1.5rem'
                            }}
                        >
                            <div className="flex items-center gap-3">
                                <Wallet size={24} color="white" />
                                <h3 style={{ margin: 0, color: 'white' }}>{t('smartBudget')}</h3>
                            </div>
                            <p style={{ margin: 0, fontSize: '0.9rem', color: 'rgba(255,255,255,0.8)' }}>
                                {t('smartBudgetDesc')}
                            </p>
                            <button
                                onClick={() => navigate('/budget', { state: { details: plan.budgetDetails } })}
                                className="btn"
                                style={{ background: 'white', color: 'var(--primary)', width: '100%', border: 'none' }}
                            >
                                {t('viewDetailedBudget') || 'View Analysis & Currency'} <ArrowRight size={18} />
                            </button>
                        </motion.div>

                        {/* Stays / Hotels (NEW) */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.05 }}
                            className="card"
                            style={{
                                background: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
                                color: 'white',
                                display: 'flex',
                                flexDirection: 'column',
                                gap: '1rem',
                                padding: '1.5rem'
                            }}
                        >
                            <div className="flex items-center gap-3">
                                <Home size={24} color="white" />
                                <h3 style={{ margin: 0, color: 'white' }}>{t('staySuggestions') || 'Stay Suggestions'}</h3>
                            </div>
                            <p style={{ margin: 0, fontSize: '0.9rem', color: 'rgba(255,255,255,0.8)' }}>
                                {t('stayDesc') || 'Explore handpicked accommodations matching your budget.'}
                            </p>
                            <button
                                onClick={() => navigate('/hotels', { state: { hotels: plan.hotelSuggestions, destination: plan.destination } })}
                                className="btn"
                                style={{ background: 'white', color: '#059669', width: '100%', border: 'none' }}
                            >
                                {t('viewStays') || 'Explore Hotels'} <ArrowRight size={18} />
                            </button>
                        </motion.div>

                        {/* 🧠 AI Magic Card (NEW) */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}
                            className="card"
                            style={{
                                background: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
                                color: 'white',
                                display: 'flex',
                                flexDirection: 'column',
                                gap: '1rem',
                                padding: '1.5rem',
                                border: 'none',
                                boxShadow: '0 10px 25px -5px rgba(245, 158, 11, 0.4)'
                            }}
                        >
                            <div className="flex items-center gap-3">
                                <Sun size={24} color="white" />
                                <h3 style={{ margin: 0, color: 'white' }}>{t('aiMagic') || 'AI Magic'}</h3>
                            </div>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
                                <button
                                    onClick={() => handleMagicClick('late')}
                                    className="btn"
                                    style={{ background: 'rgba(255,255,255,0.2)', border: '1px solid rgba(255,255,255,0.4)', color: 'white', justifyContent: 'flex-start', fontSize: '0.85rem' }}
                                >
                                    <Clock size={16} /> {t('wakeUpLate') || 'Wake up late?'}
                                </button>
                                <button
                                    onClick={() => handleMagicClick('skipped')}
                                    className="btn"
                                    style={{ background: 'rgba(255,255,255,0.2)', border: '1px solid rgba(255,255,255,0.4)', color: 'white', justifyContent: 'flex-start', fontSize: '0.85rem' }}
                                >
                                    <X size={16} /> {t('skippedPlace') || 'Skipped place?'}
                                </button>
                                <button
                                    onClick={() => handleMagicClick('overspent')}
                                    className="btn"
                                    style={{ background: 'rgba(255,255,255,0.2)', border: '1px solid rgba(255,255,255,0.4)', color: 'white', justifyContent: 'flex-start', fontSize: '0.85rem' }}
                                >
                                    <DollarSign size={16} /> {t('overspent') || 'Overspent?'}
                                </button>
                            </div>
                        </motion.div>

                        {/* Highlights */}
                        <motion.div className="card" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
                            <h3>{t('highlights')}</h3>
                            <div className="flex" style={{ flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                                {plan.highlights.map(h => (
                                    <span key={h} style={{ padding: '0.3rem 0.8rem', background: '#F3E8FF', color: '#7E22CE', borderRadius: '6px', fontSize: '0.85rem', fontWeight: 'bold' }}>
                                        {h}
                                    </span>
                                ))}
                            </div>
                        </motion.div>

                        {/* 6️⃣ Local Intelligence */}
                        {/* Live Updates (NEW) */}
                        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.15 }}>
                            <LiveContext plan={plan} />
                        </motion.div>

                        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}>
                            <LocalIntelligence data={plan.localIntelligence} />
                        </motion.div>

                        {/* Actions */}
                        <div className="flex gap-2">
                            <button
                                className="btn"
                                style={{
                                    flex: 1,
                                    background: isSaved ? 'var(--success)' : 'var(--secondary)',
                                    color: 'white'
                                }}
                                onClick={handleSave}
                            >
                                <Download size={18} /> {isSaved ? t('saved') : t('savePdf')}
                            </button>
                            <button className="btn btn-secondary" style={{ flex: 1 }} onClick={handleShare}>
                                <Share2 size={18} /> {t('share')}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Modal */}
            <AnimatePresence>
                {selectedActivity && (
                    <motion.div
                        className="modal-overlay"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={() => setSelectedActivity(null)}
                    >
                        <motion.div
                            className="modal-content"
                            initial={{ scale: 0.9, y: 20 }}
                            animate={{ scale: 1, y: 0 }}
                            exit={{ scale: 0.9, y: 20 }}
                            onClick={(e) => e.stopPropagation()}
                        >
                            <button className="modal-close" onClick={() => setSelectedActivity(null)}>
                                <X size={24} />
                            </button>

                            <div className="flex items-center gap-3">
                                <Info className="text-primary" size={24} />
                                <h2 className="modal-title">{selectedActivity.title}</h2>
                            </div>

                            <div className="detail-grid">
                                <DetailItem icon={<Clock size={16} />} label={t('hours')} value={`${selectedActivity.opening} - ${selectedActivity.closing}`} />
                                <DetailItem icon={<Ticket size={16} />} label={t('entryCost')} value={selectedActivity.cost} />
                                <DetailItem icon={<Calendar size={16} />} label={t('holidays')} value={selectedActivity.holidays} />
                                <DetailItem icon={<MapPin size={16} />} label={t('travelTime')} value={selectedActivity.travelTime} />
                            </div>

                            <div className="warning-box">
                                <div className="flex items-center gap-2" style={{ marginBottom: '0.5rem' }}>
                                    <AlertTriangle size={18} color="var(--warning)" />
                                    <strong style={{ fontSize: '0.8rem', color: '#92400E', textTransform: 'uppercase' }}>{t('warningsTips')}</strong>
                                </div>
                                <p className="warning-text">{selectedActivity.warnings}</p>
                            </div>

                            <div className="flex justify-end mt-4">
                                <button className="btn btn-primary" onClick={() => setSelectedActivity(null)}>
                                    {t('gotIt')}
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}

                {/* AI Magic Notification */}
                {magicResult && (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.8, y: 50 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.8, y: 50 }}
                        style={{
                            position: 'fixed',
                            bottom: '2rem',
                            left: '50%',
                            transform: 'translateX(-50%)',
                            zIndex: 10000,
                            width: '90%',
                            maxWidth: '500px'
                        }}
                    >
                        <div className="card" style={{
                            background: 'rgba(255, 255, 255, 0.95)',
                            backdropFilter: 'blur(10px)',
                            border: '1px solid var(--primary)',
                            boxShadow: '0 20px 50px rgba(0,0,0,0.2)',
                            padding: '1.5rem',
                            display: 'flex',
                            gap: '1rem',
                            alignItems: 'flex-start'
                        }}>
                            <div style={{ background: 'var(--primary)', padding: '0.6rem', borderRadius: '12px', color: 'white' }}>
                                <Zap size={24} />
                            </div>
                            <div style={{ flex: 1 }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                                    <h4 style={{ margin: 0, color: 'var(--primary)' }}>{t('aiMagic')} - {t('smartReschedule')}</h4>
                                    <button onClick={() => setMagicResult(null)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}>
                                        <X size={16} />
                                    </button>
                                </div>
                                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.8rem', fontStyle: 'italic' }}>
                                    {t('rescheduleTip')}
                                </p>
                                <div style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '12px', borderLeft: '4px solid var(--primary)' }}>
                                    <strong style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>
                                        {t('alternative')}
                                    </strong>
                                    <div style={{ color: 'var(--text-main)', fontWeight: '600' }}>
                                        {magicResult.alternative}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

const ActivitySlot = ({ label, data, onSelect, t }) => (
    <div className="time-slot" onClick={() => onSelect(data)}>
        <span className="slot-label">{label}</span>
        <div className="activity-title">{data.title}</div>

        <div className="meta-row">
            <span className="meta-item"><Clock size={14} /> {data.duration}</span>
            <span className="meta-item"><Ticket size={14} /> {data.cost}</span>
        </div>
        <div className="meta-row" style={{ marginTop: '-0.5rem' }}>
            <span className="meta-item"><MapPin size={14} /> {data.travelTime} {t('away')}</span>
        </div>

        <div style={{ marginTop: '1rem', display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
            {data.safeToSkip ? (
                <span className="tag tag-skip">{t('safeToSkip')}</span>
            ) : (
                <span className="tag tag-essential">{t('mustDo')}</span>
            )}
        </div>

        {data.crowdDensity && (
            <div style={{ marginTop: '0.8rem', paddingTop: '0.8rem', borderTop: '1px solid rgba(0,0,0,0.05)' }}>
                <div className="flex justify-between items-center">
                    <span style={{ fontSize: '0.75rem', fontWeight: '600', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Users size={12} /> {t('crowdDensity')}
                    </span>
                    <span style={{
                        fontSize: '0.75rem',
                        fontWeight: 'bold',
                        color: parseInt(data.crowdDensity) > 70 ? 'var(--error)' : parseInt(data.crowdDensity) > 40 ? '#F59E0B' : 'var(--success)'
                    }}>
                        {data.crowdDensity}
                    </span>
                </div>
                <div style={{ height: '4px', background: 'rgba(0,0,0,0.05)', borderRadius: '10px', marginTop: '4px', overflow: 'hidden' }}>
                    <div style={{
                        height: '100%',
                        width: data.crowdDensity,
                        background: parseInt(data.crowdDensity) > 70 ? 'var(--error)' : parseInt(data.crowdDensity) > 40 ? '#F59E0B' : 'var(--success)',
                        borderRadius: '10px'
                    }} />
                </div>
                {data.bestTime && (
                    <div style={{ marginTop: '6px', fontSize: '0.7rem', color: 'var(--primary)', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Zap size={10} fill="currentColor" /> {t('bestTimeVisit')}: {data.bestTime}
                    </div>
                )}
            </div>
        )}

        {!data.safeToSkip && (
            <div className="regret-box">
                <span className="regret-label flex items-center gap-1">
                    <Frown size={12} /> {t('fomoLevel')}: {data.regretProb}
                </span>
                <div className="regret-bar">
                    <div
                        className="regret-fill"
                        style={{ width: data.regretProb }}
                    ></div>
                </div>
            </div>
        )}
    </div>
);

const DetailItem = ({ icon, label, value }) => (
    <div className="detail-item">
        <div className="flex items-center gap-1">
            {icon}
            <span className="detail-label">{label}</span>
        </div>
        <div className="detail-value">{value}</div>
    </div>
);

export default TripPlan;

