import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
    ArrowLeft, Sun, Download, Share2, DollarSign, Clock, MapPin,
    Ticket, Frown, X, AlertTriangle, Calendar, Info
} from 'lucide-react';

const TripPlan = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const { plan } = location.state || {};
    const [selectedActivity, setSelectedActivity] = useState(null);
    const [isSaved, setIsSaved] = useState(false);

    const handleSave = () => {
        // 1. Save to LocalStorage for persistence in "My Trips" (future feature)
        const savedTrips = JSON.parse(localStorage.getItem('travelTales_trips') || '[]');
        const updatedTrips = [plan, ...savedTrips.filter(t => t.tripName !== plan.tripName)];
        localStorage.setItem('travelTales_trips', JSON.stringify(updatedTrips));

        // 2. Visual Feedback
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 3000);

        // 3. Trigger Print (which allows saving as PDF)
        // We'll wait a bit for the "Saved!" text to appear or just do it immediately
        window.print();
    };

    const handleShare = () => {
        const text = `Check out my ${plan.tripName}! Plan generated by TravelTales.`;
        if (navigator.share) {
            navigator.share({
                title: plan.tripName,
                text: text,
                url: window.location.href,
            });
        } else {
            navigator.clipboard.writeText(`${text} ${window.location.href}`);
            alert("Link copied to clipboard!");
        }
    };

    if (!plan) {
        return (
            <div className="flex justify-center items-center" style={{ minHeight: '100vh', background: 'var(--bg-body)' }}>
                <div className="text-center">
                    <h2>No Plan Found</h2>
                    <button onClick={() => navigate('/plan')} className="btn btn-primary" style={{ marginTop: '1rem' }}>
                        Start Planning
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div style={{ minHeight: '100vh', paddingBottom: '5rem', background: '#F8FAFC' }}>
            {/* Header Image */}
            <div className="trip-header" style={{
                height: '350px',
                background: `linear-gradient(to top, rgba(0,0,0,0.8), transparent), url(https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80) center/cover`,
                position: 'relative',
                color: 'white',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'flex-end',
                paddingBottom: '3rem'
            }}>
                <div className="container" style={{ position: 'relative', zIndex: 2 }}>
                    <button
                        onClick={() => navigate('/plan')}
                        style={{
                            position: 'absolute', top: '-200px', left: '0',
                            background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)',
                            border: 'none', borderRadius: '50%', width: '40px', height: '40px',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            cursor: 'pointer', color: 'white'
                        }}
                    >
                        <ArrowLeft size={24} />
                    </button>

                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                        <div className="flex gap-2" style={{ marginBottom: '1rem' }}>
                            <span style={{ background: 'var(--primary)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold', textTransform: 'uppercase' }}>
                                {plan.vibe} Trip
                            </span>
                            <span style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold' }}>
                                {plan.dates}
                            </span>
                        </div>
                        <h1 style={{ color: 'white', marginBottom: '0.5rem', fontSize: '4rem' }}>{plan.destination}</h1>
                        <p style={{ fontSize: '1.2rem', opacity: 0.9 }}>
                            Your personalized {plan.travelers} adventure. Est. Budget: <span style={{ color: '#86EFAC', fontWeight: 'bold' }}>${plan.budgetSummary.total} Total</span>
                        </p>
                    </motion.div>
                </div>
            </div>

            <div className="container" style={{ marginTop: '-3rem', position: 'relative', zIndex: 10 }}>
                <div className="trip-grid" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 2.5fr) minmax(0, 1fr)', gap: '2rem' }}>

                    {/* Itinerary Column */}
                    <div className="itinerary-list">
                        {plan.itinerary.map((day, index) => (
                            <motion.div
                                key={day.day}
                                className="day-card"
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: index * 0.1 }}
                            >
                                {/* Day Header */}
                                <div className="day-header">
                                    <div>
                                        <h3 style={{ margin: 0 }}>Day {day.day}</h3>
                                        <p style={{ margin: 0, fontSize: '0.9rem' }}>{day.date}</p>
                                    </div>
                                    <div className="chip" style={{ background: 'white', fontSize: '0.85rem' }}>
                                        <Sun size={16} style={{ color: '#F59E0B' }} /> {day.weather}
                                    </div>
                                </div>

                                {/* Timeline Grid */}
                                <div className="timeline-grid">
                                    <ActivitySlot label="Morning 🌅" data={day.morning} onSelect={setSelectedActivity} />
                                    <ActivitySlot label="Afternoon ☀️" data={day.afternoon} onSelect={setSelectedActivity} />
                                    <ActivitySlot label="Evening 🌙" data={day.evening} onSelect={setSelectedActivity} />
                                </div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Sidebar */}
                    <div className="sidebar" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                        {/* Budget Card */}
                        <motion.div className="card" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
                            <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                <DollarSign size={20} color="var(--success)" /> Budget
                            </h3>
                            <div style={{ marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
                                <div className="flex justify-between" style={{ fontSize: '0.9rem' }}>
                                    <span>Tier</span>
                                    <strong>{plan.budgetSummary.level}</strong>
                                </div>
                                <div className="flex justify-between" style={{ fontSize: '0.9rem' }}>
                                    <span>Per Person</span>
                                    <strong>${plan.budgetSummary.perPerson}</strong>
                                </div>
                                <hr style={{ border: 'none', borderTop: '1px solid var(--border-light)' }} />
                                <div className="flex justify-between" style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                                    <span>Total</span>
                                    <span style={{ color: 'var(--success)' }}>${plan.budgetSummary.total}</span>
                                </div>
                            </div>
                        </motion.div>

                        {/* Highlights */}
                        <motion.div className="card" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
                            <h3>Highlights</h3>
                            <div className="flex" style={{ flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                                {plan.highlights.map(h => (
                                    <span key={h} style={{ padding: '0.3rem 0.8rem', background: '#F3E8FF', color: '#7E22CE', borderRadius: '6px', fontSize: '0.85rem', fontWeight: 'bold' }}>
                                        {h}
                                    </span>
                                ))}
                            </div>
                        </motion.div>

                        {/* Actions */}
                        <div className="flex gap-2">
                            <button
                                className="btn"
                                style={{
                                    flex: 1,
                                    background: isSaved ? 'var(--success)' : 'var(--secondary)',
                                    color: 'white'
                                }}
                                onClick={handleSave}
                            >
                                <Download size={18} /> {isSaved ? 'Saved!' : 'Save PDF'}
                            </button>
                            <button className="btn btn-secondary" style={{ flex: 1 }} onClick={handleShare}>
                                <Share2 size={18} /> Share
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Modal */}
            <AnimatePresence>
                {selectedActivity && (
                    <motion.div
                        className="modal-overlay"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={() => setSelectedActivity(null)}
                    >
                        <motion.div
                            className="modal-content"
                            initial={{ scale: 0.9, y: 20 }}
                            animate={{ scale: 1, y: 0 }}
                            exit={{ scale: 0.9, y: 20 }}
                            onClick={(e) => e.stopPropagation()}
                        >
                            <button className="modal-close" onClick={() => setSelectedActivity(null)}>
                                <X size={24} />
                            </button>

                            <div className="flex items-center gap-3">
                                <Info className="text-primary" size={24} />
                                <h2 className="modal-title">{selectedActivity.title}</h2>
                            </div>

                            <div className="detail-grid">
                                <DetailItem icon={<Clock size={16} />} label="Hours" value={`${selectedActivity.opening} - ${selectedActivity.closing}`} />
                                <DetailItem icon={<Ticket size={16} />} label="Entry Cost" value={selectedActivity.cost} />
                                <DetailItem icon={<Calendar size={16} />} label="Holidays" value={selectedActivity.holidays} />
                                <DetailItem icon={<MapPin size={16} />} label="Travel Time" value={selectedActivity.travelTime} />
                            </div>

                            <div className="warning-box">
                                <div className="flex items-center gap-2" style={{ marginBottom: '0.5rem' }}>
                                    <AlertTriangle size={18} color="var(--warning)" />
                                    <strong style={{ fontSize: '0.8rem', color: '#92400E', textTransform: 'uppercase' }}>Warnings & Tips</strong>
                                </div>
                                <p className="warning-text">{selectedActivity.warnings}</p>
                            </div>

                            <div className="flex justify-end mt-4">
                                <button className="btn btn-primary" onClick={() => setSelectedActivity(null)}>
                                    Got it!
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

const ActivitySlot = ({ label, data, onSelect }) => (
    <div className="time-slot" onClick={() => onSelect(data)}>
        <span className="slot-label">{label}</span>
        <div className="activity-title">{data.title}</div>

        <div className="meta-row">
            <span className="meta-item"><Clock size={14} /> {data.duration}</span>
            <span className="meta-item"><Ticket size={14} /> {data.cost}</span>
        </div>
        <div className="meta-row" style={{ marginTop: '-0.5rem' }}>
            <span className="meta-item"><MapPin size={14} /> {data.travelTime} away</span>
        </div>

        <div style={{ marginTop: '1rem', display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
            {data.safeToSkip ? (
                <span className="tag tag-skip">Safe to Skip</span>
            ) : (
                <span className="tag tag-essential">Must Do</span>
            )}
        </div>

        {!data.safeToSkip && (
            <div className="regret-box">
                <span className="regret-label flex items-center gap-1">
                    <Frown size={12} /> FOMO LEVEL: {data.regretProb}
                </span>
                <div className="regret-bar">
                    <div
                        className="regret-fill"
                        style={{ width: data.regretProb }}
                    ></div>
                </div>
            </div>
        )}
    </div>
);

const DetailItem = ({ icon, label, value }) => (
    <div className="detail-item">
        <div className="flex items-center gap-1">
            {icon}
            <span className="detail-label">{label}</span>
        </div>
        <div className="detail-value">{value}</div>
    </div>
);

export default TripPlan;
