import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
    ArrowLeft, Sun, Download, Share2, DollarSign, Clock, MapPin,
    Ticket, Frown, X, AlertTriangle, Calendar, Info
} from 'lucide-react';

import MapExploration from './MapExploration';
import LocalIntelligence from './LocalIntelligence';
import BudgetManager from './BudgetManager';
import { useLanguage } from './LanguageContext';

const TripPlan = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const { t, language } = useLanguage();
    const { plan } = location.state || {};
    const [selectedActivity, setSelectedActivity] = useState(null);
    const [isSaved, setIsSaved] = useState(false);

    const languages = [
        { code: 'en', name: 'English' },
        { code: 'es', name: 'Español' },
        { code: 'fr', name: 'Français' },
        { code: 'zh', name: '中文' },
        { code: 'ar', name: 'العربية' },
        { code: 'hi', name: 'हिन्दी' },
        { code: 'de', name: 'Deutsch' },
        { code: 'pt', name: 'Português' },
        { code: 'ja', name: '日本語' },
        { code: 'ru', name: 'Русский' }
    ];

    const handleSave = () => {
        setIsSaved(true);
        setTimeout(() => setIsSaved(false), 3000);
        window.print();
    };

    const handleShare = () => {
        const text = `Check out my ${plan.tripName}! Plan generated by TravelTales.`;
        if (navigator.share) {
            navigator.share({
                title: plan.tripName,
                text: text,
                url: window.location.href,
            });
        } else {
            navigator.clipboard.writeText(`${text} ${window.location.href}`);
            alert(t('copyAlert'));
        }
    };

    if (!plan) {
        return (
            <div className="flex justify-center items-center" style={{ minHeight: '100vh', background: 'var(--bg-body)' }}>
                <div className="text-center">
                    <h2>{t('noPlanFound')}</h2>
                    <button onClick={() => navigate('/plan')} className="btn btn-primary" style={{ marginTop: '1rem' }}>
                        {t('startPlanning')}
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div style={{ minHeight: '100vh', paddingBottom: '5rem', background: '#F8FAFC', paddingTop: '80px' }}>
            {/* Header Image */}
            <div className="trip-header" style={{
                height: '350px',
                background: `linear-gradient(to top, rgba(0,0,0,0.8), transparent), url(https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80) center/cover`,
                position: 'relative',
                color: 'white',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'flex-end',
                paddingBottom: '3rem'
            }}>
                <div className="container" style={{ position: 'relative', zIndex: 2 }}>
                    <button
                        onClick={() => navigate('/plan')}
                        style={{
                            position: 'absolute', top: '-130px', left: '0',
                            background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)',
                            border: 'none', borderRadius: '50%', width: '40px', height: '40px',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            cursor: 'pointer', color: 'white'
                        }}
                    >
                        <ArrowLeft size={24} />
                    </button>

                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                        <div className="flex gap-2" style={{ marginBottom: '1rem' }}>
                            <span style={{ background: 'var(--primary)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold', textTransform: 'uppercase' }}>
                                {plan.vibe} {t('tripVibe')}
                            </span>
                            <span style={{ background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(5px)', padding: '0.2rem 0.8rem', borderRadius: '50px', fontSize: '0.8rem', fontWeight: 'bold' }}>
                                {plan.dates}
                            </span>
                        </div>
                        <h1 style={{ color: 'white', marginBottom: '0.5rem', fontSize: '4rem' }}>{plan.destination}</h1>
                        <p style={{ fontSize: '1.2rem', opacity: 0.9 }}>
                            Your personalized {plan.travelers} adventure. Est. Budget: <span style={{ color: '#86EFAC', fontWeight: 'bold' }}>${plan.budgetSummary.total} {t('total')}</span>
                        </p>
                    </motion.div>
                </div>
            </div>

            <div className="container" style={{ marginTop: '-3rem', position: 'relative', zIndex: 10 }}>
                {/* 5️⃣ Map-Based Exploration */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    style={{ marginBottom: '2rem' }}
                >
                    <MapExploration plan={plan} />
                </motion.div>

                <div className="trip-grid" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 2fr) minmax(0, 1.2fr)', gap: '2rem' }}>

                    {/* Itinerary Column */}
                    <div className="itinerary-list">
                        {plan.itinerary.map((day, index) => (
                            <motion.div
                                key={day.day}
                                className="day-card"
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: index * 0.1 }}
                            >
                                {/* Day Header */}
                                <div className="day-header">
                                    <div>
                                        <h3 style={{ margin: 0 }}>{t('day')} {day.day}</h3>
                                        <p style={{ margin: 0, fontSize: '0.9rem' }}>{day.date}</p>
                                    </div>
                                    <div className="chip" style={{ background: 'white', fontSize: '0.85rem' }}>
                                        <Sun size={16} style={{ color: '#F59E0B' }} /> {day.weather}
                                    </div>
                                </div>

                                {/* Timeline Grid */}
                                <div className="timeline-grid">
                                    <ActivitySlot label={t('morning')} data={day.morning} onSelect={setSelectedActivity} t={t} />
                                    <ActivitySlot label={t('afternoon')} data={day.afternoon} onSelect={setSelectedActivity} t={t} />
                                    <ActivitySlot label={t('evening')} data={day.evening} onSelect={setSelectedActivity} t={t} />
                                </div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Sidebar */}
                    <div className="sidebar" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                        {/* 💰 Smart Budget Manager */}
                        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
                            <BudgetManager details={plan.budgetDetails} />
                        </motion.div>

                        {/* Highlights */}
                        <motion.div className="card" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}>
                            <h3>{t('highlights')}</h3>
                            <div className="flex" style={{ flexWrap: 'wrap', gap: '0.5rem', marginTop: '1rem' }}>
                                {plan.highlights.map(h => (
                                    <span key={h} style={{ padding: '0.3rem 0.8rem', background: '#F3E8FF', color: '#7E22CE', borderRadius: '6px', fontSize: '0.85rem', fontWeight: 'bold' }}>
                                        {h}
                                    </span>
                                ))}
                            </div>
                        </motion.div>

                        {/* 6️⃣ Local Intelligence */}
                        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}>
                            <LocalIntelligence data={plan.localIntelligence} />
                        </motion.div>

                        {/* Actions */}
                        <div className="flex gap-2">
                            <button
                                className="btn"
                                style={{
                                    flex: 1,
                                    background: isSaved ? 'var(--success)' : 'var(--secondary)',
                                    color: 'white'
                                }}
                                onClick={handleSave}
                            >
                                <Download size={18} /> {isSaved ? t('saved') : t('savePdf')}
                            </button>
                            <button className="btn btn-secondary" style={{ flex: 1 }} onClick={handleShare}>
                                <Share2 size={18} /> {t('share')}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Modal */}
            <AnimatePresence>
                {selectedActivity && (
                    <motion.div
                        className="modal-overlay"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={() => setSelectedActivity(null)}
                    >
                        <motion.div
                            className="modal-content"
                            initial={{ scale: 0.9, y: 20 }}
                            animate={{ scale: 1, y: 0 }}
                            exit={{ scale: 0.9, y: 20 }}
                            onClick={(e) => e.stopPropagation()}
                        >
                            <button className="modal-close" onClick={() => setSelectedActivity(null)}>
                                <X size={24} />
                            </button>

                            <div className="flex items-center gap-3">
                                <Info className="text-primary" size={24} />
                                <h2 className="modal-title">{selectedActivity.title}</h2>
                            </div>

                            <div className="detail-grid">
                                <DetailItem icon={<Clock size={16} />} label={t('hours')} value={`${selectedActivity.opening} - ${selectedActivity.closing}`} />
                                <DetailItem icon={<Ticket size={16} />} label={t('entryCost')} value={selectedActivity.cost} />
                                <DetailItem icon={<Calendar size={16} />} label={t('holidays')} value={selectedActivity.holidays} />
                                <DetailItem icon={<MapPin size={16} />} label={t('travelTime')} value={selectedActivity.travelTime} />
                            </div>

                            <div className="warning-box">
                                <div className="flex items-center gap-2" style={{ marginBottom: '0.5rem' }}>
                                    <AlertTriangle size={18} color="var(--warning)" />
                                    <strong style={{ fontSize: '0.8rem', color: '#92400E', textTransform: 'uppercase' }}>{t('warningsTips')}</strong>
                                </div>
                                <p className="warning-text">{selectedActivity.warnings}</p>
                            </div>

                            <div className="flex justify-end mt-4">
                                <button className="btn btn-primary" onClick={() => setSelectedActivity(null)}>
                                    {t('gotIt')}
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

const ActivitySlot = ({ label, data, onSelect, t }) => (
    <div className="time-slot" onClick={() => onSelect(data)}>
        <span className="slot-label">{label}</span>
        <div className="activity-title">{data.title}</div>

        <div className="meta-row">
            <span className="meta-item"><Clock size={14} /> {data.duration}</span>
            <span className="meta-item"><Ticket size={14} /> {data.cost}</span>
        </div>
        <div className="meta-row" style={{ marginTop: '-0.5rem' }}>
            <span className="meta-item"><MapPin size={14} /> {data.travelTime} {t('away')}</span>
        </div>

        <div style={{ marginTop: '1rem', display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
            {data.safeToSkip ? (
                <span className="tag tag-skip">{t('safeToSkip')}</span>
            ) : (
                <span className="tag tag-essential">{t('mustDo')}</span>
            )}
        </div>

        {!data.safeToSkip && (
            <div className="regret-box">
                <span className="regret-label flex items-center gap-1">
                    <Frown size={12} /> {t('fomoLevel')}: {data.regretProb}
                </span>
                <div className="regret-bar">
                    <div
                        className="regret-fill"
                        style={{ width: data.regretProb }}
                    ></div>
                </div>
            </div>
        )}
    </div>
);

const DetailItem = ({ icon, label, value }) => (
    <div className="detail-item">
        <div className="flex items-center gap-1">
            {icon}
            <span className="detail-label">{label}</span>
        </div>
        <div className="detail-value">{value}</div>
    </div>
);

export default TripPlan;

